DROP TABLE Jobs CASCADE CONSTRAINTS;

DROP TABLE Applicant CASCADE CONSTRAINTS;

DROP TABLE Subscription CASCADE CONSTRAINTS;

DROP TABLE Accounts CASCADE CONSTRAINTS;

DROP TABLE Qualifications CASCADE CONSTRAINTS;

DROP TABLE Department CASCADE CONSTRAINTS;

DROP TABLE Employees CASCADE CONSTRAINTS;
