/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edmond.jobbank.mavenproject1;

import java.io.*;
import java.sql.*;
import org.apache.ibatis.jdbc.ScriptRunner;

/**
 *
 * @author Brian
 */
public class Account extends javax.swing.JFrame {

    private static FrontPage frontpage;
    private static Account accountpage;
    static Connection con;
    private static String[] account;
    /**
     * Creates new form Account
     */
    private Account() {
        initComponents();
    }
    
    public static Account getInstance(FrontPage fPanel, Connection conn, String[] accountS) {
        if(accountpage == null) {
            accountpage = new Account();
            con = conn;
            frontpage = fPanel;
            account = accountS;
        }
        return accountpage;
    }
    
    public void updateText() {
        UserUsername_jlabel.setText(account[1]);
        UserPassword_jlabel.setText(account[2]);
        UserName_jlabel.setText(account[3]);
        UserEmail_jlabel.setText(account[4]);
        UserBirthdate_jlabel.setText(account[5]);
        UserAddress_jlabel.setText(account[6]);
        UserPhone_jlabel.setText(account[7]);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Close_button = new javax.swing.JButton();
        Phone_jlabel = new javax.swing.JLabel();
        Password_jlabel = new javax.swing.JLabel();
        Email_jlabel = new javax.swing.JLabel();
        Name_jlabel = new javax.swing.JLabel();
        Username_jlabel = new javax.swing.JLabel();
        Birthdate_jlabel = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Address_jlabel = new javax.swing.JLabel();
        UserUsername_jlabel = new javax.swing.JLabel();
        UserPassword_jlabel = new javax.swing.JLabel();
        UserSubscription_jlabel = new javax.swing.JLabel();
        UserName_jlabel = new javax.swing.JLabel();
        UserAddress_jlabel = new javax.swing.JLabel();
        UserBirthdate_jlabel = new javax.swing.JLabel();
        UserPhone_jlabel = new javax.swing.JLabel();
        Subscription_jlabel = new javax.swing.JLabel();
        Back_Button = new javax.swing.JButton();
        UserEmail_jlabel = new javax.swing.JLabel();
        ChangeSubscription_Button = new javax.swing.JButton();
        Qualifications_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Close_button.setText("Close");
        Close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_buttonActionPerformed(evt);
            }
        });

        Phone_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Phone_jlabel.setText("Phone");

        Password_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Password_jlabel.setText("Password");

        Email_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Email_jlabel.setText("Email");

        Name_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Name_jlabel.setText("Name");

        Username_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Username_jlabel.setText("Username");

        Birthdate_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Birthdate_jlabel.setText("Birthdate");

        Title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Title.setText("Account Details");

        Address_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Address_jlabel.setText("Address");

        UserUsername_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        UserPassword_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        UserSubscription_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        UserName_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        UserAddress_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        UserBirthdate_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        UserPhone_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Subscription_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Subscription_jlabel.setText("Subscription");

        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        UserEmail_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ChangeSubscription_Button.setText("Change Subscription");
        ChangeSubscription_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeSubscription_ButtonActionPerformed(evt);
            }
        });

        Qualifications_button.setText("Qualifications");
        Qualifications_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Qualifications_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Address_jlabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UserAddress_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Birthdate_jlabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                    .addComponent(UserBirthdate_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Name_jlabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UserName_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Phone_jlabel)
                                        .addComponent(Email_jlabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(UserPhone_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                        .addComponent(UserEmail_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Subscription_jlabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UserSubscription_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Password_jlabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UserPassword_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Username_jlabel)
                                    .addGap(93, 93, 93)
                                    .addComponent(UserUsername_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ChangeSubscription_Button, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 166, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Qualifications_button)
                        .addGap(52, 52, 52))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Close_button)
                    .addComponent(Back_Button))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Back_Button)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title)
                    .addComponent(Qualifications_button))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username_jlabel)
                    .addComponent(UserUsername_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_jlabel)
                    .addComponent(UserPassword_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserSubscription_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Subscription_jlabel))
                .addGap(21, 21, 21)
                .addComponent(ChangeSubscription_Button)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name_jlabel)
                    .addComponent(UserName_jlabel))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Birthdate_jlabel)
                    .addComponent(UserBirthdate_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Address_jlabel)
                    .addComponent(UserAddress_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Phone_jlabel)
                    .addComponent(UserPhone_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserEmail_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email_jlabel))
                .addGap(35, 35, 35)
                .addComponent(Close_button))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_buttonActionPerformed
        ScriptRunner sr = new ScriptRunner(con);
        try {
            sr.runScript(new BufferedReader(new FileReader("C:\\Users\\Edmond\\Documents\\Workspace\\cps510\\jobbankuimaven\\scripts\\DropTables.sql")));
        } catch (FileNotFoundException e) {
             e.printStackTrace();
        }
        System.exit(0);
    }//GEN-LAST:event_Close_buttonActionPerformed

    private void ChangeSubscription_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeSubscription_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeSubscription_ButtonActionPerformed

    private void Qualifications_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Qualifications_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Qualifications_buttonActionPerformed

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        accountpage.setVisible(false);
        frontpage.setVisible(true);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address_jlabel;
    private javax.swing.JButton Back_Button;
    private javax.swing.JLabel Birthdate_jlabel;
    private javax.swing.JButton ChangeSubscription_Button;
    private javax.swing.JButton Close_button;
    private javax.swing.JLabel Email_jlabel;
    private javax.swing.JLabel Name_jlabel;
    private javax.swing.JLabel Password_jlabel;
    private javax.swing.JLabel Phone_jlabel;
    private javax.swing.JButton Qualifications_button;
    private javax.swing.JLabel Subscription_jlabel;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel UserAddress_jlabel;
    private javax.swing.JLabel UserBirthdate_jlabel;
    private javax.swing.JLabel UserEmail_jlabel;
    private javax.swing.JLabel UserName_jlabel;
    private javax.swing.JLabel UserPassword_jlabel;
    private javax.swing.JLabel UserPhone_jlabel;
    private javax.swing.JLabel UserSubscription_jlabel;
    private javax.swing.JLabel UserUsername_jlabel;
    private javax.swing.JLabel Username_jlabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
