/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edmond.jobbank.mavenproject1;

import java.io.*;
import java.sql.*;
import org.apache.ibatis.jdbc.ScriptRunner;

/**
 *
 * @author Brian
 */
public class FrontPage extends javax.swing.JFrame {
    
    private static FrontPage frontpage;
    private static Intro introPanel;
    static Connection con;
    private static String[] account;
    /**
     * Creates new form FrontPage
     */
    private FrontPage() {
        initComponents();
    }
    
    public static FrontPage getInstance(Intro iPanel, Connection conn, String[] accountS) {
        if(frontpage == null) {
            frontpage = new FrontPage();
        }
        con = conn;
        introPanel = iPanel;
        account = accountS;
        return frontpage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrontPage_jpanel = new javax.swing.JPanel();
        Jobs_Button = new javax.swing.JButton();
        Close_Button = new javax.swing.JButton();
        Account_Button = new javax.swing.JButton();
        Logout_Button = new javax.swing.JButton();
        Introduction_Scroll = new javax.swing.JScrollPane();
        Introduction_text = new javax.swing.JTextArea();
        Welcome_Label = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jobs_Button.setText("Jobs");
        Jobs_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jobs_ButtonActionPerformed(evt);
            }
        });

        Close_Button.setText("Close");
        Close_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_ButtonActionPerformed(evt);
            }
        });

        Account_Button.setText("My Account");
        Account_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_ButtonActionPerformed(evt);
            }
        });

        Logout_Button.setText("Logout");
        Logout_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_ButtonActionPerformed(evt);
            }
        });

        Introduction_text.setColumns(20);
        Introduction_text.setRows(5);
        Introduction_text.setText("Welcome!\n\nAt the Job Bank you will be able to find thousands of opportunities\nin which you will be able to choose from. No matter what, the Job\nBank will always have a option for you. From start ups to Large\ncorporations, all the jobs can be found here.\n\nUse the My Accounts button to go to you account and see your\npersonal information and edit your settings. You can also change\nyour subscription status here to unlock more features.\n\nUse the Jobs button to go and see our large and diverse Job Bank.\nHere you will be able to find all sorts of jobs and the one just\nright for you.\n\nGood Luck!");
        Introduction_Scroll.setViewportView(Introduction_text);

        Welcome_Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Welcome_Label.setText("Welcome");

        Name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Name.setText("           ");

        javax.swing.GroupLayout FrontPage_jpanelLayout = new javax.swing.GroupLayout(FrontPage_jpanel);
        FrontPage_jpanel.setLayout(FrontPage_jpanelLayout);
        FrontPage_jpanelLayout.setHorizontalGroup(
            FrontPage_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrontPage_jpanelLayout.createSequentialGroup()
                .addComponent(Close_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(FrontPage_jpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Account_Button)
                .addGap(173, 173, 173)
                .addComponent(Jobs_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(FrontPage_jpanelLayout.createSequentialGroup()
                .addGroup(FrontPage_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrontPage_jpanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(Welcome_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Name))
                    .addGroup(FrontPage_jpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Introduction_Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        FrontPage_jpanelLayout.setVerticalGroup(
            FrontPage_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrontPage_jpanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(FrontPage_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(Welcome_Label))
                .addGap(18, 18, 18)
                .addGroup(FrontPage_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Account_Button)
                    .addComponent(Jobs_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Introduction_Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(FrontPage_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logout_Button)
                    .addComponent(Close_Button)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FrontPage_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FrontPage_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jobs_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jobs_ButtonActionPerformed
        Jobs jobsPanel = Jobs.getInstance(this, con);
        jobsPanel.setVisible(true);
        jobsPanel.updateText();
        this.setVisible(false);
    }//GEN-LAST:event_Jobs_ButtonActionPerformed

    private void Close_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_ButtonActionPerformed
        ScriptRunner sr = new ScriptRunner(con);
        try {
            sr.runScript(new BufferedReader(new FileReader("C:\\Users\\Edmond\\Documents\\Workspace\\cps510\\jobbankuimaven\\scripts\\DropTables.sql")));
        } catch (FileNotFoundException e) {
             e.printStackTrace();
        }
        System.exit(0);
    }//GEN-LAST:event_Close_ButtonActionPerformed

    private void Account_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_ButtonActionPerformed
        Account accountPanel = Account.getInstance(this, con, account);
        accountPanel.setVisible(true);
        accountPanel.updateText();
        this.setVisible(false);
    }//GEN-LAST:event_Account_ButtonActionPerformed

    private void Logout_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_ButtonActionPerformed
        frontpage.setVisible(false);
        introPanel.setVisible(true);
    }//GEN-LAST:event_Logout_ButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account_Button;
    private javax.swing.JButton Close_Button;
    private javax.swing.JPanel FrontPage_jpanel;
    private javax.swing.JScrollPane Introduction_Scroll;
    private javax.swing.JTextArea Introduction_text;
    private javax.swing.JButton Jobs_Button;
    private javax.swing.JButton Logout_Button;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Welcome_Label;
    // End of variables declaration//GEN-END:variables
}
