/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edmond.jobbank.mavenproject1;

import java.io.*;
import java.sql.*;
import org.apache.ibatis.jdbc.ScriptRunner;
/**
 *
 * @author Brian
 */
public class Jobs extends javax.swing.JFrame {
    static Connection con;
    private static FrontPage frontpage;
    private static Jobs jobpage;
    /**
     * Creates new form Jobs
     */
    private Jobs() {
        initComponents();
    }
    
    public static Jobs getInstance(FrontPage fPage, Connection conn) {
        if(jobpage == null) {
            con = conn;
            frontpage = fPage;
            jobpage = new Jobs();
        }
        return jobpage;
    }
    
    public void updateText() {
        String output ="Job ID \t Work Period \t Company \t Salary\t Job Title\t\t Job Location\t Job Type\t Job Deadline\n";
        try {
            String query = "SELECT * FROM jobs";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()) {
               for(int j = 0 ; j < 8; j++) {
                    output += rs.getString(j+1)+"\t";
                } 
               output +="\n";
            }
            JobList_text.setText(output);
        } catch (SQLException e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jobs_jpanel = new javax.swing.JPanel();
        JobList_jpanel = new javax.swing.JPanel();
        JobList_scroll = new javax.swing.JScrollPane();
        JobList_text = new javax.swing.JTextArea();
        Apply_button = new javax.swing.JButton();
        Apply_text = new javax.swing.JTextField();
        Title_jlabel = new javax.swing.JLabel();
        Close_button = new javax.swing.JButton();
        Back_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JobList_text.setColumns(20);
        JobList_text.setRows(5);
        JobList_scroll.setViewportView(JobList_text);

        javax.swing.GroupLayout JobList_jpanelLayout = new javax.swing.GroupLayout(JobList_jpanel);
        JobList_jpanel.setLayout(JobList_jpanelLayout);
        JobList_jpanelLayout.setHorizontalGroup(
            JobList_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JobList_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );
        JobList_jpanelLayout.setVerticalGroup(
            JobList_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JobList_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        Apply_button.setText("Apply");
        Apply_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apply_buttonActionPerformed(evt);
            }
        });

        Apply_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apply_textActionPerformed(evt);
            }
        });

        Title_jlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Title_jlabel.setText("Job Search");

        Close_button.setText("Close");
        Close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_buttonActionPerformed(evt);
            }
        });

        Back_button.setText("Back");
        Back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jobs_jpanelLayout = new javax.swing.GroupLayout(Jobs_jpanel);
        Jobs_jpanel.setLayout(Jobs_jpanelLayout);
        Jobs_jpanelLayout.setHorizontalGroup(
            Jobs_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jobs_jpanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(Jobs_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title_jlabel)
                    .addComponent(JobList_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jobs_jpanelLayout.createSequentialGroup()
                        .addComponent(Apply_text, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Apply_button)
                        .addGap(8, 8, 8)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(Jobs_jpanelLayout.createSequentialGroup()
                .addGroup(Jobs_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Close_button)
                    .addComponent(Back_button))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Jobs_jpanelLayout.setVerticalGroup(
            Jobs_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jobs_jpanelLayout.createSequentialGroup()
                .addComponent(Back_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title_jlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jobs_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apply_button)
                    .addComponent(Apply_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JobList_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Close_button))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Jobs_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Jobs_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Apply_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apply_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apply_textActionPerformed

    private void Close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_buttonActionPerformed
        ScriptRunner sr = new ScriptRunner(con);
        try {
            sr.runScript(new BufferedReader(new FileReader("C:\\Users\\Edmond\\Documents\\Workspace\\cps510\\jobbankuimaven\\scripts\\DropTables.sql")));
        } catch (FileNotFoundException e) {
             e.printStackTrace();
        }
        System.exit(0);
    }//GEN-LAST:event_Close_buttonActionPerformed

    private void Back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_buttonActionPerformed
        jobpage.setVisible(false);
        frontpage.setVisible(true);
    }//GEN-LAST:event_Back_buttonActionPerformed

    private void Apply_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apply_buttonActionPerformed
        System.out.println(Apply_text.getText()+" applied!");
    }//GEN-LAST:event_Apply_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apply_button;
    private javax.swing.JTextField Apply_text;
    private javax.swing.JButton Back_button;
    private javax.swing.JButton Close_button;
    private javax.swing.JPanel JobList_jpanel;
    private javax.swing.JScrollPane JobList_scroll;
    private javax.swing.JTextArea JobList_text;
    private javax.swing.JPanel Jobs_jpanel;
    private javax.swing.JLabel Title_jlabel;
    // End of variables declaration//GEN-END:variables

}
