/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jobbank;

/**
 *
 * @author Brian
 */
public class Qualifications extends javax.swing.JFrame {

    /**
     * Creates new form Qualifications
     */
    public Qualifications() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back_button = new javax.swing.JButton();
        Degree_jlabel = new javax.swing.JLabel();
        Years_jlabel = new javax.swing.JLabel();
        License_jlabel = new javax.swing.JLabel();
        Resume_jlabel = new javax.swing.JLabel();
        CoverLetter_jlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resume_text = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        CoverLetter_text = new javax.swing.JTextArea();
        Degree_text = new javax.swing.JTextField();
        Years_text = new javax.swing.JTextField();
        License_text = new javax.swing.JTextField();
        Close_button = new javax.swing.JButton();
        Title_jlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back_button.setText("Back");
        Back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_buttonActionPerformed(evt);
            }
        });

        Degree_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Degree_jlabel.setText("Degree");

        Years_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Years_jlabel.setText("Years Experience");

        License_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        License_jlabel.setText("License");

        Resume_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Resume_jlabel.setText("Resume");

        CoverLetter_jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CoverLetter_jlabel.setText("Cover Letter");

        Resume_text.setColumns(20);
        Resume_text.setRows(5);
        jScrollPane1.setViewportView(Resume_text);

        CoverLetter_text.setColumns(20);
        CoverLetter_text.setRows(5);
        jScrollPane2.setViewportView(CoverLetter_text);

        Degree_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Degree_textActionPerformed(evt);
            }
        });

        Years_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Years_textActionPerformed(evt);
            }
        });

        Close_button.setText("Close");

        Title_jlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Title_jlabel.setText("Qualifications");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Back_button)
                        .addGap(187, 187, 187)
                        .addComponent(Title_jlabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Resume_jlabel)
                            .addComponent(CoverLetter_jlabel)
                            .addComponent(Years_jlabel)
                            .addComponent(License_jlabel)
                            .addComponent(Degree_jlabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(Degree_text)
                            .addComponent(Years_text)
                            .addComponent(License_text)))
                    .addComponent(Close_button))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Back_button)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Title_jlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(Degree_jlabel)
                .addGap(5, 5, 5)
                .addComponent(Degree_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Years_jlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Years_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(License_jlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(License_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Resume_jlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CoverLetter_jlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(Close_button))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back_buttonActionPerformed

    private void Degree_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Degree_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Degree_textActionPerformed

    private void Years_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Years_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Years_textActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_button;
    private javax.swing.JButton Close_button;
    private javax.swing.JLabel CoverLetter_jlabel;
    private javax.swing.JTextArea CoverLetter_text;
    private javax.swing.JLabel Degree_jlabel;
    private javax.swing.JTextField Degree_text;
    private javax.swing.JLabel License_jlabel;
    private javax.swing.JTextField License_text;
    private javax.swing.JLabel Resume_jlabel;
    private javax.swing.JTextArea Resume_text;
    private javax.swing.JLabel Title_jlabel;
    private javax.swing.JLabel Years_jlabel;
    private javax.swing.JTextField Years_text;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
